### ISSUE TITLE
Can't understand how this thing goes 

### ISSUE THREAD

**Issue by scindo07** [caturmahdialfurqon/TENEO-NODE-CLI#1]
Can you add a Youtube tutorial on how to set up this thing in python and also with the auto log in and recconect

Thank You.

**Comment by caturmahdialfurqon** [comment]
Sorry I don't have a YouTube channel, I thought I could help you here.
so you need fuction auto login and auto reconnect.

## Autoreconnect

```python
    async def on_close():
        global socket
        socket = None
        print("WebSocket disconnected")
        stop_pinging()
        await reconnect_websocket(user_id)

    async def on_error(error):
        print("WebSocket error:", error)

    await on_open()
    try:
        await on_message()
    except Exception as e:
        await on_error(e)
    finally:
        await on_close()

async def reconnect_websocket(user_id):
    print("Attempting to reconnect...")
    await asyncio.sleep(5)  # Wait before reconnecting
    await connect_websocket(user_id)
```

## Auto Login

```python
async def auto_login():
    account_data = await get_account_data()
    if account_data.get('email') and account_data.get('password'):
        await get_user_id()
```

and

```python
if __name__ == "__main__":
    asyncio.run(main())
    asyncio.get_event_loop().call_later(3600, auto_login)
```
![CleanShot 2024-10-22 at 20 31 40](https://github.com/user-attachments/assets/52d03825-a087-4f26-b0e4-27b386b1c260)

**Comment by caturmahdialfurqon** [comment]
[requirements.txt](https://github.com/user-attachments/files/17477213/requirements.txt)

**Comment by caturmahdialfurqon** [comment]
I have updated the script in Python code.
![Screenshot 2024-10-22 at 20 56 21](https://github.com/user-attachments/assets/972b1868-4c81-4d8b-8188-c1e7dc40626d)
![Screenshot 2024-10-22 at 20 51 25](https://github.com/user-attachments/assets/4b0933bd-0ddf-45b9-9652-f90b69f7bbc0)

**Comment by caturmahdialfurqon** [comment]
Is there anything else you would like to discuss? If not, I will consider this matter closed.
