### ISSUE TITLE
how to multi account?

### ISSUE THREAD

**Issue by khamdanf** [caturmahdialfurqon/teneo-node-cli#2]
can we do how to multi account?

**Comment by caturmahdialfurqon** [comment]
It's easy to set up, it only requires a few functions, but your account will be `banned`. The maximum running per IP is 3 accounts, more than that all your accounts will be `banned`.
I don't recommend it.

**Comment by caturmahdialfurqon** [comment]
I will close this issue and if there are other questions, Feel free to ask questions, share ideas in the discussion session. visit [discussions](https://github.com/caturmahdialfurqon/teneo-node-cli/discussions)
